### ISSUE TITLE
Here is my "theme" file you asked me on Youtube (Docteur Controller)

### ISSUE THREAD

**Issue by DocteurController** [Nielk1/VSCView#14]
Like you, i have some notification issues on Youtube. So i'm gonna try here to share with you my theme file for the VSC View.
Here is the link : 
https://wetransfer.com/downloads/a4d1f476359ffaed3ec3e994193ab71620190623144137/b29d25

Hope it will work this time.
Have a good day !

**Comment by Nielk1** [comment]
@DocteurController Excellent, thank you!

Indeed, there was no notification on YouTube but an instant notification here.

Your theme is now part of the project and will appear in the next release version.  The theme will be called "Docteur".  The next release will take some time as I am in the middle of a major code update that adds support for Sony DS4 controllers.

I will link your YouTube channel in the theme's "about" note unless you would like a different URL linked.  I am closing this issue but feel free to reply here anyway if you would like.

![image](https://user-images.githubusercontent.com/1022047/60038635-80a53d00-967a-11e9-85a9-2302e7e1394e.png)
