### ISSUE TITLE
steam controller connect but no showing on VSCView

### ISSUE THREAD

**Issue by Blaze99** [Nielk1/VSCView#2]
Steam controller connected using the dongle steam running in big picture mode no game running tried all options under controller. but no luck in getting the controller to show up on the software

**Comment by Nielk1** [comment]
Does the Controller menu have no items listed or do none of the items work when selected?
Does the Reload Controllers menu option change anything?
Did you make sure you selected a theme from the Theme menu to display the output on?

**Comment by Nielk1** [comment]
The entire backend has been replaced in v0.5.0.0 so any existing issues like this are invalid and really should be fixed.  If they're still going on re-report.
