### ISSUE TITLE
VSC View

### ISSUE THREAD

**Issue by minimaster3468** [Nielk1/VSCView#30]
Heya, whenever I  try to open VSCView.exe nothing pops up. I have tried turning off my anitvirus and but as soon as I open it nothing happens.. even though I'm sure a grees controller or something is meant to show up. Any solutions?

**Comment by Nielk1** [comment]
Please check if VSCView.exe is listed in your process list in Task Manager.  If it is, then we will need to dig a bit deeper to find why nothing is showing up.  If it is not, we can check the Event Viewer for a possible error.  In the Windows Event Viewer, select Windows Logs > Application and look for any recent errors related to `VSCView` or `.net`.

**Comment by minimaster3468** [comment]
VCSView wasn't anywhere in my Task Manager after trying to open it up. So I looked in the Event Viewer and it seems that there is an Application Error with it. Now that I have found the Error... what do I do to fix it?

**Comment by Nielk1** [comment]
I need to know the contents of that error to know that.  It could be a missing dependency or I might need to make a change to the program itself,

**Comment by minimaster3468** [comment]
Could you add me on discord so I oculd send you screenshots and do things there?
Sim#6909
