### ISSUE TITLE
High CPU usage after some time

### ISSUE THREAD

**Issue by kotborealis** [Nielk1/VSCView#5]
VSCView uses about ~60% of CPU after some time.

Steam Controller plugged in using USB cable (not wireless dongle).

It's also stuck in one position and does not respond to Steam Controller.

![](https://i.imgur.com/Qjb34xe.png)

**Comment by kotborealis** [comment]
After submitting this issue I decided to try reloading and switching controller in VSCView context menu and  some fiddling VSCView started to respond to controller inputs and CPU usage dropped drastically to about 2%.

**Comment by Nielk1** [comment]
Major changes have occurred that should resolve this.  Please re-open this issue (or make a new one) if the issue is not fixed or returns.
