### ISSUE TITLE
New Steam client update broke gyro recognition.

### ISSUE THREAD

**Issue by vikingsail** [Nielk1/VSCView#55]
In the recent Steam client update it seems Valve has changed the way how they collect position data. The current VSCview version (0.5.0.0) stopped responding to my Steam Controller's gyro movement. The accelerometer is working fine. 
The last date I can confirm it was working was 23. Oct. If anyone else knows a later date of confirmed working status, feel free to comment here.

**Comment by maxy3d** [comment]
I had the same issue.... when I uses my SC thru Bluetooth and Dongle, the gyro is working fine in the new steam v2.0+ ( Settings -> Controller -> Calibration and Advanced Settings -> Gyro Calibration) You can see the speed and the controller direction is working fine.  The VSCview 0.5.0 app, some times recognized my gyro when using the dongle but, thru Bluetooth the gyro does not respond nor shows any movement on the app. The accelerometer, in the other hand , its working correctly thru both ways of connection (Bluetooth and dongle).
