### ISSUE TITLE
I could have a new graphic suggestion for your VSCView

### ISSUE THREAD

**Issue by DocteurController** [Nielk1/VSCView#6]
Hi Nielk1,

I've opened a (french) Steam Controller's channel few months ago and i started doing it by using my own graphic gifs i've made to show which buttons were pressed in live. But it was a pretty boring editing work to display each command this way. So i start to use your software which really ease my work. But i'm still missing the presentation of my gif that i'd like to suggest you for you VSCView. I think it could help to make it more concise and clear, especially for back paddles and triggers.
You can have a look on what it looks like at this adress : 
https://youtu.be/C7xgXeJ2R0w?t=697
It's a mix of 2-3 official SC's picture that i have also a bit retouched with Gimp.

Tell me what you think about it ! And thank you a lot for your great software which helped me a lot.

Docteur Controller.

**Comment by Nielk1** [comment]
@DocteurController I know my reply is very late here, I had shelved this project until pull requests fixing some bugs brought it back to my attention.  If you have a visual theme you'd like I can create it if given the needed image files.

**Comment by DocteurController** [comment]
Hi Nielk1,

Thank you for the reply and no worries if it's late, at least it forced me to custom your great software by myself. 
You can see the result on my last videos if you have a little time to loose :
https://www.youtube.com/watch?v=q1x1BvykZt4 
(i just made most of buttons more red since this precise video)
And i've made a french tutorial video to explain how to customize your software with an english commentary under it to also give a good idea on how to do it to english people. You can see it here : https://www.youtube.com/watch?v=7PNiDyqAbHM

Now we're talking about that, i realized i forgot to mention the link to your software under my last videos (i was used to do it till the tutorial video on it), i'm gonna fix this impoliteness right now. Sorry about that.

i hope my english is understandable, i usually do many mistakes i usually see too late.

**Comment by Nielk1** [comment]
Closing this.  Doctor Controller has graciously provided his custom theme files and they have been integrated into the repository for the next release pending further refinement and code updates.
